Classes/Domain/Repository/RemoteIdMappingRepository.php
Classes/Handler/FileUploadHandler.php
Classes/ObjectManager.php

[FEATURE]Added getFiles endpoint, fixes in uploadFile

---

Classes/Handler/CrudHandler.php
Classes/Handler/FileUploadHandler.php

[FEATURE] added configuration for relation fields

---

Classes/Handler/CrudHandler.php
Classes/Handler/FileUploadHandler.php

[FEATURE] added relation context checking

---

Classes/Handler/FileUploadHandler.php

[FEATURE] added endpoint for image references

---

Classes/BootstrapDispatcher.php
Classes/Handler/AuthenticationHandler.php

[BUGFIX] authentication fixes

---

Classes/Authentication/AuthenticationProvider.php
Classes/BootstrapDispatcher.php
Classes/Dispatcher/Dispatcher.php
Classes/Handler/AuthenticationHandler.php
Classes/Hook/ClearCachePostProc.php
ext_localconf.php

[TASK] added clearing cache hook, fixed wrong headers

---

Classes/Event/BeforeDataHandlingEvent.php
Classes/Handler/CrudHandler.php

[FEATURE] added beforeDataHandling event

---

Classes/Event/BeforeDataHandlingEvent.php
Classes/Handler/CrudHandler.php

[BUGFIX] set tablename for delete record method

---

Classes/Event/BeforeDataHandlingEvent.php
Classes/Handler/CrudHandler.php

[BUGFIX] do not remove from mapping and pending relations

---

Classes/Handler/CrudHandler.php
Classes/Handler/Exception/MissingArgumentException.php
Classes/Handler/Exception/MissingArgumentsException.php

[FEATURE] new function to resolve pid depending of language installation

---

Classes/Handler/CrudHandler.php

[BUGFIX] added empty array as condition

---

Classes/Handler/BatchHandler.php
Classes/Handler/CrudHandler.php
Classes/Handler/FileUploadHandler.php

[BUGFIX] fixed handlers and create/update methods

---

Classes/Handler/FileUploadHandler.php

[BUGFIX] added countryCode for file references

---

Classes/Handler/CrudHandler.php
ext_tables.sql

[FEATURE] added record hashing functionallity

---

Classes/Handler/BatchHandler.php

[BUGFIX] change function arguments to correct one

---

Classes/Handler/CrudHandler.php

[FEATURE] improved relationContextTrue option, exclude sys_language_uid from relation fields

---

Classes/Handler/FileUploadHandler.php

[BUGFIX] files fetching recursively

---

Classes/DataHandling/Operation/AbstractRecordOperation.php

[BUGFIX] make sure single-value array is transformed to scalar value

---

Classes/Router/HttpRequestRouter.php

[BUGFIX] Make empty endpoint accessible

---

Classes/RequestHandler/AbstractRecordRequestHandler.php
Documentation/Implementing/Rest/Index.rst

[FEATURE] Add HTTP header option to disable reference index update

---

Classes/DataHandling/Operation/AbstractRecordOperation.php
Tests/Functional/DataHandling/Operation/UpdateRecordOperationTest.php

Adds an extra check of updated fields with foreign field relations, and removes relations not present in the updated value.

[BUGFIX] delete removed relations

---

Documentation/Implementing/Extending/Index.rst

[BUGFIX] Fix typo

---

ext_emconf.php

Prepare for version ''1.1.3''.

[RELEASE] Prepare for version ''1.1.3''

---

Classes/Router/HttpRequestRouter.php

To avoid an exception "Call to a member function checkRecord() on null" in ResourceFactory.

[BUGFIX] make TSFE->sys_page available in TYPO3 v11

---

ext_emconf.php

Prepare for version ''1.1.6''.

[RELEASE] Prepare for version ''1.1.6''

---

Configuration/Commands.php

Fixes: #91
Ensure that CLI commands work in TYPO3 v9.

[BUGFIX] Ensure that CLI commands work in TYPO3 v9

---

Classes/DataHandling/Operation/Event/Handler/PersistFileDataEventHandler.php

While mass downloading image files by URL I got various [cURL errors (52, 28, 35)](https://curl.se/libcurl/c/libcurl-errors.html).
By changing method PersistFileDataEventHandler->handleUrlInput() to use TYPO3s Guzzle wrapper class \TYPO3\CMS\Core\Http\RequestFactory, as recommended in the [docs](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/RestRequests/Index.html), instead of directly using the Guzzle Client all problems seem to have disappeared directly.

[BUGFIX] Fix cURL errors when processing URL input
